language: python
python: 3.8
os: linux

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - ./scripts/init_test

script:
  - coverage run -m unittest discover

after_success:
  - coveralls
