language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
os: linux
install:
  - pip install -r ./requirements.txt
before_script:
  - |
    cat << EOF > "$HOME"/.aws/credentials
    [default]
    aws_access_key_id = 111111111
    aws_secret_access_key = 111111111
    [root]
    aws_access_key_id = 111111111
    aws_secret_access_key = 111111111
    EOF
  - |
    cat << EOF > "$HOME"/.aws/config
    [default]
    region = ap-southeast-2
    [root]
    region = ap-southeast-2
    EOF
script:
  - python -m unittest discover
