name: Lint

on: [push, pull_request]

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pydocstyle
        run: pip install pydocstyle
      - name: Pydocstyle check
        run: pydocstyle fzfaws
